### ISSUE TITLE
"Force required" is ill-defined

### ISSUE THREAD

**Issue by EliasHasle** [Mugen87/yuka#3] opened 2019-07-29 14:20 UTC
https://github.com/Mugen87/yuka/blob/f0ea1ea5529307f23c09d2a860e7a8196fa490c1/src/steering/behaviors/SeekBehavior.js#L51

The calculation gives a difference of velocities. Given the assumption in SteeringBehavior.js that mass=1, it is still only the force needed to move from one velocity to the other in one time unit. This simple calculation biases it to a position past the target, with the bias depending on the magnitude of the force.

SteeringManager considers the maximal force of the vehicle and applies the behaviors by priority, but note that if the Seek behavior were really prioritized, it should know the maximal vehicle force before its calculation, and adjust the calculation accordingly. The simple calculation could be used as is, but scaling the magnitude to the max force.

Alternatively, the max force could be used even better, to minimize the bias, as I did in a school project once. **This is for 2D, but can perhaps inspire a similar 3D solution**:

````
function seekAcc(pa,va, pg, aMax) {
	let d = delta(pa,pg);
	let r = length(d);
	//Important check to avoid division by zero:
	if (r === 0) {
		return [0,0];
	}	
	let dir = scale(d, 1/r);
	
	//RT coordinates will be useful:
	let vr = dot(va,dir);
	let vt = dot(va, rotate(dir, 0.5*Math.PI));
	let theta = angle(dir);
	
	//Trusting to find a fixed point by iteration
	//(this decision must be verified mathematically):
	let ar = aMax, at=0;
	let dat = Infinity;
	while (ar !==0 && Math.abs(dat) > 0.0001*aMax) {
		let srt = (vr**2+2*r*ar)**0.5;
		let t1 = (-vr-srt)/ar;
		let t2 = (-vr+srt)/ar;
		let t = t1 > 0 ? t1 : t2;
		let atn = Math.max(-aMax,Math.min(aMax,-2*vt/t));
		dat = atn-at;
		at = atn;
		ar = (aMax**2 -(at**2))**0.5;
	}
	
	return rotate([ar,at], theta);
}
````

Rough derivation:

```
	First, estimate time to impact from vr and aMax only:
	r-vr*t-0.5*aMax*t**2 = 0
	t = (-vr +-sqrt(vr**2+2*r*aMax))/aMax
	
	Using this t, find the offset caused by the tangential velocity:
	offset = vt*t
	
	Try to compensate for the offset, by applying an acceleration opposing vt:
	offset = vt*t + 0.5*at*t**2 = 0
	Assuming t is the same:
	at = -2*vt/t
	
	But then
	ar = sqrt(aMax**2-(2*vt/t)**2) < aMax
	and
	t = (-vr +-sqrt(vr**2+2*r*ar))/ar
```

You can see it in action here, in comparison to a naïve seek:
https://eliashasle.github.io/swarm2d-experiments/Behavior_Seek_comparison.html
(Just refresh the page to get different random scenarios)

**Comment by Mugen87** [comment] 2019-07-29 18:09
Hi Elias, nice to see you around here :wave:

our code is based on a reference from game development. The original C++ code from Mat Buckland (_Programming Game AI by Example_) looks like so:

```c++
//------------------------------- Seek -----------------------------------
//
//  Given a target, this behavior returns a steering force which will
//  direct the agent towards the target
//------------------------------------------------------------------------
Vector2D SteeringBehavior::Seek(Vector2D TargetPos)
{
  Vector2D DesiredVelocity = Vec2DNormalize(TargetPos - m_pVehicle->Pos())
                            * m_pVehicle->MaxSpeed();

  return (DesiredVelocity - m_pVehicle->Velocity());
}
```
In general, we prefer to work with references whenever possible. Is your code section based on some sort of  publication (book, paper, article) or is it a personal invention?

In any event, the engine's current seek behavior worked fine like in many commercial applications. I'm afraid I do not yet understand the benefits of your approach. Especially since your code is computational way more expensive. Keep in mind that we are not interested in a physically perfect solution. It's more important to have a compromise of reasonable behavior and good performance.

**Comment by EliasHasle** [comment] 2019-07-29 18:44
Nice to be here too. :-)

You are right that my method is sort of a "personal invention". Not exactly rocket science, but at least discovered independently by me. It is more expensive, but tends to converge fast. I have not proven the convergence yet. I think I would google "Banach fixed point theorem" if I were to investigate it.

The benefit is that the seek hits the target faster. The naïve seek will often spiral around the target because it does not correct for the position consequences of the initial velocity.

Anyway, a first improvement step, a more conservative one, will be to let seek know what the vehicle max acceleration is, so that it can output a vector of that magnitude, minimizing the position offset given the present method.

**Comment by Mugen87** [comment] 2019-07-29 19:07
> Anyway, a first improvement step, a more conservative one, will be to let seek know what the vehicle max acceleration is, so that it can output a vector of that magnitude, minimizing the position offset given the present method.

Okay, I see now where you are heading. Unfortunately, `SteeringManager` is responsible to ensure the maximum amount of force a vehicle is able to produce (or to power itself) is not exceeded. By design, single steering behaviors should not evaluate `Vehicle.maxForce`. So in some sense you hit a limitation of the engine's chose approaches^^.

**Comment by EliasHasle** [comment] 2019-07-29 19:26
SteeringManager would still be able to filter out too large values, but the steering behavior would get some idea of a "budget" for its decision.

**Comment by Mugen87** [comment] 2019-07-30 08:29
We also worked with that reference^^. It's also used by the mentioned book.

**Comment by Mugen87** [comment] 2019-07-31 12:37
Closing. We stick to the current implementation for now but keep your suggestion in mind. In any event, thanks for your feedback!

**Closed by Mugen87** 2019-07-31 12:37 UTC
Labels: Type: Needs Investigation

**Comment by EliasHasle** [comment] 2019-07-31 13:21
No problem!
